INSERT INTO users(username, password, enabled)
    VALUES ('guest', '12345', TRUE );
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY)
    VALUES ('guest', 'ROLE_USER');
INSERT INTO MENUS(START_DATE, END_DATE)
    VALUES ('2016-10-1', '2016-10-7');
INSERT INTO FOOD(FOOD_NAME, PRICE, DESCRIPTION, FOOD_DATE, MENU_ID)
    VALUES ('Koprovka', 55, 'Celkem se da', '2016-10-2', (SELECT ID FROM MENUS FETCH FIRST ROW ONLY));
INSERT INTO RESERVATION(PERSON, FOOD_ID) VALUES ('guest', (SELECT ID FROM FOOD FETCH FIRST ROW ONLY ));
