CREATE TABLE FOOD (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FOOD_NAME VARCHAR(50) NOT NULL,
    PRICE DECIMAL NOT NULL,
    DESCRIPTION VARCHAR(250),
    FOOD_DATE DATE,
    MENU_ID INT REFERENCES menus(id) ON DELETE CASCADE
);

CREATE TABLE MENUS (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL
);